export const ADD_CHUNCK = 'ADD_CHUNCK';
export const CLEAR_CHUNCKS = 'CLEAR_CHUNCKS';
export const SET_ORDER = 'SET_ORDER';
export const REBUILD_CHUNCKS = 'REBUILD_CHUNCKS';
export const SET_ACTIVE_CHUNCK = 'SET_ACTIVE_CHUNCK';